name: CI
on:
  push:
    branches:
      - master
      - develop
      - "release/**"
jobs:
  buildAndTest:
    name: build and test
    runs-on: macos-latest
    strategy:
      matrix:
        project: ["PassLibrary.xcodeproj"]
        scheme: ["PassLibrary-Package"]
        destination: ["platform=iOS Simulator,OS=13.5,name=iPhone 11 Pro Max"]
    steps:
      - uses: actions/checkout@v1
      - name: Build and Test
        run: |
          xcodebuild test -project "${project}" -scheme "${scheme}" -destination "${destination}"
        env:
          destination: ${{ matrix.destination }}
          scheme: ${{ matrix.scheme }}
          project: ${{ matrix.project }}
